name: Scala CI

on: push

jobs:

  build_jar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Scala
      uses: olafurpg/setup-scala@v11
      with:
        java-version: 21
    - name: Build Fat JAR
      run: sbt assembly

  unit_test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: 21
      - name: Run Unit Tests
        run: sbt "testOnly HelloTest"

  integration_test:
      runs-on: ubuntu-latest
      needs: [build_jar, unit_test]
      steps:
      - uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: 21
      - name: Run Integration Tests
        run: sbt "testOnly SimpleTestServerIntegrationTest"