name: Scala CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: 21
    - name: Run tests
      run: sbt clean build

  unit_test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 21
      - name: Run Unit Tests
        run: sbt testOnly HelloTest

  integration_test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 21
      - name: Run Integration Tests
        run: sbt testOnly SimpleTestServerIntegrationTest
