name: Scala CI

on: push

jobs:

  build_jar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: 21
    - name: Run tests
      run: sbt assembly

  unit_test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 21
      - name: Run Unit Tests
        run: sbt testOnly HelloTest

  integration_test:
      runs-on: ubuntu-latest
      needs: [build, unit_test]
      steps:
      - uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 21
      - name: Run Integration Tests
        run: sbt testOnly SimpleTestServerIntegrationTest